# Generated by Django 4.0.6 on 2022-08-02 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('aadharNumber', models.CharField(blank=True, max_length=25, null=True)),
                ('phoneNumber', models.CharField(blank=True, max_length=15, null=True)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('taluka', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=300, null=True)),
                ('haveGasConnection', models.BooleanField(default=False)),
                ('belongToSC', models.BooleanField(default=False)),
            ],
        ),
    ]
